
TR.Props = {
	["models/props_borealis/bluebarrel001.mdl"] =				 	{ price = 83, health = 59, v_off = Vector(), a_off = Angle(), cat = "Plastic" },
	["models/props_interiors/vendingmachinesoda01a.mdl"] = 			{ price = 840, health = 600, v_off = Vector(), a_off = Angle(), cat = "Plastic" },
	["models/props_interiors/vendingmachinesoda01a_door.mdl"] = 	{ price = 280, health = 200, v_off = Vector(), a_off = Angle(), cat = "Plastic" },
	["models/props_junk/trafficcone001a.mdl"] = 					{ price = 14, health = 10, v_off = Vector(), a_off = Angle(), cat = "Plastic" },
	["models/props_junk/trashbin01a.mdl"] = 						{ price = 28, health = 20, v_off = Vector(), a_off = Angle(), cat = "Plastic" },
	["models/props_junk/plasticcrate01a.mdl"] = 					{ price = 14, health = 10, v_off = Vector(), a_off = Angle(), cat = "Plastic" },

	["models/props_c17/shelfunit01a.mdl"] =				 			{ price = 108, health = 90, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituretable001a.mdl"] = 					{ price = 72, health = 60, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer001a_chunk05.mdl"] = 			{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer001a_chunk06.mdl"] = 			{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer002a.mdl"] = 					{ price = 18, health = 15, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_junk/wood_crate002a.mdl"] = 						{ price = 71, health = 59, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_junk/wood_pallet001a.mdl"] =				 		{ price = 24, health = 20, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_junk/cardboard_box004a_gib01.mdl"] = 			{ price = 1.2, health = 1, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_junk/cardboard_box001a.mdl"] = 					{ price = 6, health = 5, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_junk/wood_crate001a.mdl"] = 						{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituretable003a.mdl"] = 					{ price = 48, health = 40, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer003a.mdl"] = 					{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer001a_chunk03.mdl"] =			{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer001a_chunk02.mdl"] =			{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer001a_chunk01.mdl"] =			{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredrawer001a.mdl"] =					{ price = 24, health = 20, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furniturecupboard001a.mdl"] = 				{ price = 600, health = 500, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_junk/cardboard_box003a.mdl"] = 					{ price = 6, health = 5, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituredresser001a.mdl"] = 				{ price = 180, health = 150, v_off = Vector(), a_off = Angle(), cat = "Wood" },
	["models/props_c17/furnituretable002a.mdl"] = 					{ price = 54, health = 45, v_off = Vector(), a_off = Angle(), cat = "Wood" },

	["models/props_borealis/borealis_door001a.mdl"] =				{ price = 66, health = 55, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_borealis/mooring_cleat01.mdl"] = 				{ price = 24, health = 20, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/canister01a.mdl"] = 							{ price = 72, health = 60, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/canister02a.mdl"] = 							{ price = 60, health = 50, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/canister_propane01a.mdl"] = 					{ price = 108, health = 90, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/furniturebathtub001a.mdl"] = 				{ price = 1080, health = 900, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/furniturebed001a.mdl"] = 					{ price = 180, health = 150, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/furniturewashingmachine001a.mdl"] = 			{ price = 330, health = 275, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/oildrum001.mdl"] = 							{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/oildrum001_explosive.mdl"] = 				{ price = 42, health = 35, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/pulleywheels_small01.mdl"] = 				{ price = 120, health = 100, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/pulleywheels_large01.mdl"] = 				{ price = 180, health = 150, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_debris/metal_panel02a.mdl"] = 					{ price = 45, health = 37, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_debris/metal_panel01a.mdl"] = 					{ price = 180, health = 150, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_interiors/radiator01a.mdl"] =					{ price = 72, health = 60, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_interiors/refrigerator01a.mdl"] = 				{ price = 479, health = 399, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_interiors/refrigeratordoor01a.mdl"] = 			{ price = 48, health = 40, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_interiors/refrigeratordoor02a.mdl"] = 			{ price = 30, health = 25, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_junk/metalbucket01a.mdl"] = 						{ price = 9.6, health = 8, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_junk/metalbucket02a.mdl"] = 						{ price = 18, health = 15, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_junk/metalgascan.mdl"] = 						{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_junk/trashdumpster02.mdl"] = 					{ price = 1199, health = 999, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_junk/trashdumpster01a.mdl"] = 					{ price = 540, health = 450, v_off = Vector(), a_off = Angle(), cat = "Metal" },
	["models/props_junk/sawblade001a.mdl"] = 						{ price = 60, health = 50, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_junk/trashdumpster02b.mdl"] = 					{ price = 60, health = 50, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_wasteland/kitchen_counter001c.mdl"] = 			{ price = 360, health = 300, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_wasteland/kitchen_counter001a.mdl"] = 			{ price = 240, health = 200, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_wasteland/kitchen_counter001b.mdl"] = 			{ price = 239., health = 199, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_wasteland/kitchen_counter001d.mdl"] = 			{ price = 300., health = 250, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/fence01a.mdl"] = 							{ price = 6, health = 5, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/fence01b.mdl"] = 							{ price = 48, health = 40, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/fence02a.mdl"] = 							{ price = 6, health = 5, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/fence02b.mdl"] = 							{ price = 6, health = 5, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/fence03a.mdl"] = 							{ price = 6, health = 5, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/fence04a.mdl"] = 							{ price = 6, health = 5, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_c17/furniturestove001a.mdl"] = 					{ price = 1800, health = 1500, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_lab/blastdoor001a.mdl"] = 						{ price = 110, health = 92, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 
	["models/props_lab/blastdoor001c.mdl"] = 						{ price = 212, health = 177, v_off = Vector(), a_off = Angle(), cat = "Metal" }, 

	["models/props_c17/concrete_barrier001a.mdl"] = 				{ price = 90, health = 75, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 
	["models/props_c17/gravestone001a.mdl"] = 						{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 
	["models/props_c17/gravestone002a.mdl"] = 						{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 
	["models/props_c17/gravestone003a.mdl"] = 						{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 
	["models/props_c17/gravestone004a.mdl"] =						{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 
	["models/props_c17/gravestone_cross001b.mdl"] = 				{ price = 36, health = 30, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 
	["models/props_junk/cinderblock01a.mdl"] = 						{ price = 39, health = 33, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 
	["models/props_wasteland/medbridge_post01.mdl"] = 				{ price = 4768, health = 3973, v_off = Vector(), a_off = Angle(), cat = "Concrete" }, 

	["models/props_c17/furniturecouch001a.mdl"] = 					{ price = 360, health = 300, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_c17/furniturecouch002a.mdl"] = 					{ price = 840, health = 700, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_combine/breenglobe.mdl"] = 						{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_combine/breendesk.mdl"] = 						{ price = 1200, health = 1000, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_combine/breenchair.mdl"] = 						{ price = 24, health = 20, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_combine/breenglobe.mdl"] = 						{ price = 12, health = 10, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/combine_helicopter/helicopter_bomb01.mdl"] = 			{ price = 42, health = 35, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_interiors/furniture_couch02a.mdl"] = 			{ price = 216, health = 180, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_interiors/furniture_lamp01a.mdl"] = 				{ price = 18, health = 15, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_interiors/sinkkitchen01a.mdl"] = 				{ price = 42, health = 35, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_lab/kennel_physics.mdl"] = 						{ price = 42, health = 35, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_lab/filecabinet02.mdl"] = 						{ price = 90, health = 75, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_vehicles/tire001b_truck.mdl"] = 					{ price = 90, health = 75, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_vehicles/tire001c_car.mdl"] = 					{ price = 30, health = 25, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_vehicles/apc_tire001.mdl"] = 					{ price = 600, health = 500, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_trainstation/trainstation_clock001.mdl"] = 		{ price = 600, health = 500, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_wasteland/barricade001a.mdl"] = 					{ price = 30, health = 25, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_wasteland/barricade002a.mdl"] = 					{ price = 30, health = 25, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_wasteland/light_spotlight01_lamp.mdl"] = 		{ price = 600, health = 500, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_wasteland/wheel01.mdl"] = 						{ price = 58, health = 48, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_wasteland/wheel01a.mdl"] = 						{ price = 91, health = 76, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_wasteland/wheel02a.mdl"] = 						{ price = 1200, health = 1000, v_off = Vector(), a_off = Angle(), cat = "Random" }, 
	["models/props_wasteland/wheel02b.mdl"] = 						{ price = 960, health = 800, v_off = Vector(), a_off = Angle(), cat = "Random" }

};

TR.Weapons = {
	
};

TR.Entities = {
	
};

